# Generated by Django 4.0.4 on 2022-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_footer_footer_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_page',
            field=models.SmallIntegerField(choices=[(1, 'Conduct'), (2, 'Privacy'), (3, 'Security'), (4, 'Cookies'), (5, 'Help'), (6, 'Advice')]),
        ),
    ]
