@startuml data_classes

left to right direction
hide empty fields
hide empty methods

models <-up- services

package "Models" as models <<Rectangle>>  {

class "Users" as users
users : +First_name : string
users : +Last_name : string
users : +Email : string
users : +Created : datetime
users : +Last_logon : datetime
users : +Bio : string
users : +Image_link : string
users : +Active : boolean


class "Items" as items
items : +Sale_type : integer
items : +Price_mimimum : float
items : +Price_fixed : float
items : +Seller : Users
items : +Condition : string
items : +Name : string
items : +Description : string
items : +Show_in_catalog : boolean
items : +Date_Ends : datetime
items : +Created : datetime
items : +Edited : datetime

class "Offers" as offers
offers : +Offer_by : Users
offers : +Item : Items
offers : +Amount : float
offers : +Active : boolean

class "Payments" as payments
payments : +Payee : Users
payments : +Seller : Users
payments : +Item : Items
payments : +Amount : float
payments : +Delivery_address : string
payments : +Delivery_address : string
payments : +Delivery_city : string
payments : +Delivery_postalcode : string
payments : +Delivery_country : Contries

class "Item tags" as itemtags
itemtags : +Item : Items
itemtags : +Tag : Tags

class "Item images" as itemimages
itemimages : +Item : Items
itemimages : +Url : string

class "Tags" as tags
tags : +Name : string
tags : +Created : datetime

class "Countries" as country
country : +Code : string
country : +Name Icelandic : string
country : +Name ISO3166 : string

class "Ratings" as ratings
ratings : +From : Users
ratings : +To : Users
ratings : +Item : Items
ratings : +Rating : integer
ratings : +Details : string

class "Messages" as messages
messages : +From : Users
messages : +To : Users
messages : +Sent : datetime
messages : +Recived : datetime
messages : +Subject : string
messages : +Text : string
}

'users -right-> items : Seller
'items -right-> payments : Item sold
'itemimages -up-> items : Item has images
'items --> itemtags : Item has tags
'itemtags --> tags
'items --> offers : Item has offers
'offers --> users : Bid by
'payments -left-> users : Payee
'payments -left-> users : Seller
'payments -down-> country : Ship to country
'ratings --> users : Rater
'ratings --> users : Rated
'ratings --> items : Rating for
'messages --> users : From
'messages --> users : To
'messages --> items : About

services <-up- views

package "Services" as services <<Cloud>>  {


class "Items service" as getItems
getItems : +get_items()

class "Offers service" as getOffers
getOffers : +get_offers()

class "Ratings service" as getRatings
getRatings : +get_ratings()

class "Messages service" as getMessage
getMessage : +get_messages()

class "Profile service" as getProfile
getProfile : +get_profile()

class "Payment service" as getPayments
getPayments : +get_payments()

class "Tags service" as getTags
getTags : +get_tags()

}


package "Views" as views <<Database>>  {

class "Items View" as viewItems

class "Offers View" as viewOffers

class "Ratings View" as viewRatings

class "Messages View" as viewMessages

class "Profile View" as viewProfile

class "Payment View" as viewPayment

class "Tags View" as viewTags

}


@enduml