
@startuml

left to right direction


rectangle "Users" as U {
    actor "Buyer" as A1
    actor "Seller" as A2
    actor "Admin" as A3
}

rectangle "Authentication" as AU {
    usecase "Email" as UC1
    usecase "Password" as UC2
}

actor "System" as A4
U -d-> UC1
U -d-> UC2
UC1 --> A4
UC2 --> A4
A4 .-> U : <<extends>>


@enduml
