# Generated by Django 4.0.4 on 2022-05-02 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSalesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('buyItNow', models.BooleanField(default=False)),
                ('auction', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_minimum', models.FloatField(default=0)),
                ('price_fixed', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=10000)),
                ('show_in_catalog', models.BooleanField(default=False)),
                ('date_ends', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(default=django.utils.timezone.now)),
                ('Condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemcondition')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemcategory')),
                ('sale_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemsalestype')),
            ],
        ),
    ]
