# Generated by Django 4.0.4 on 2022-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
