# Generated by Django 4.0.4 on 2022-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_itemimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
