# Generated by Django 4.0.4 on 2022-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rename_condition_item_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hitcount',
            field=models.IntegerField(default=0),
        ),
    ]
