# Generated by Django 4.0.4 on 2022-05-05 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_item_show_in_catalog_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
