# Generated by Django 4.0.4 on 2022-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_offer_created'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-hitcount', 'show_in_catalog'], name='item_item_hitcoun_e60e7c_idx'),
        ),
    ]
