# Generated by Django 4.0.4 on 2022-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_offer_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_accepted_offer',
            field=models.BooleanField(default=True),
        ),
    ]
