# Generated by Django 4.0.4 on 2022-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_item_has_accepted_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='has_accepted_offer',
            field=models.BooleanField(default=False),
        ),
    ]
