# Generated by Django 4.0.4 on 2022-05-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='checkout_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
