# Generated by Django 4.0.4 on 2022-05-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_offer_checkout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='checkout_id',
        ),
    ]
