# Generated by Django 4.0.4 on 2022-05-02 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 19, 34, 40, 884658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 19, 34, 40, 884658, tzinfo=utc)),
        ),
    ]
