# Generated by Django 4.0.4 on 2022-05-02 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_items_created_alter_items_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 19, 47, 17, 289343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 19, 47, 17, 289343, tzinfo=utc)),
        ),
    ]
