# Generated by Django 4.0.4 on 2022-05-02 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_items_created_alter_items_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 20, 4, 38, 914001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 20, 4, 38, 914001, tzinfo=utc)),
        ),
    ]
