# Generated by Django 4.0.4 on 2022-05-02 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_itemcategory_alter_items_created_alter_items_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 20, 5, 28, 739830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 20, 5, 28, 739830, tzinfo=utc)),
        ),
    ]
