# Generated by Django 4.0.4 on 2022-05-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=150)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
