# Generated by Django 4.0.4 on 2022-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='credit_card_num',
            new_name='credit_card_number',
        ),
    ]
