# Generated by Django 4.0.4 on 2022-05-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='credit_card_num',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='cvv',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='expiration_month',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='expiration_year',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
