# Generated by Django 4.0.4 on 2022-05-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_item_has_accepted_offer'),
        ('checkout', '0002_rename_credit_card_num_checkout_credit_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='name',
        ),
        migrations.AddField(
            model_name='checkout',
            name='credit_card_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='offer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.offer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='credit_card_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cvv',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='expiration_month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='expiration_year',
            field=models.IntegerField(choices=[(1, 2015), (2, 2016), (3, 2017), (4, 2018), (5, 2019), (6, 2020), (7, 2021), (8, 2022), (9, 2023), (10, 2024), (11, 2025), (12, 2026), (13, 2027), (14, 2028)]),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review_text',
            field=models.TextField(max_length=10000),
        ),
    ]
