# Generated by Django 4.0.4 on 2022-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_checkout_item_remove_checkout_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
