# Generated by Django 4.0.4 on 2022-05-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_credit_card_num_checkout_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='review_rating',
        ),
        migrations.AddField(
            model_name='userreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None),
            preserve_default=False,
        ),
    ]
