# Generated by Django 4.0.4 on 2022-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_credit_card_num_checkout_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='credit_card_num',
        ),
        migrations.AddField(
            model_name='checkout',
            name='credit_card_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
