# Generated by Django 4.0.4 on 2022-05-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_userreview_review_rating_userreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='checkout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout'),
        ),
    ]
