# Generated by Django 4.0.4 on 2022-05-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkout_is_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryId', models.CharField(max_length=10)),
                ('countryName', models.CharField(max_length=500)),
                ('countryNameIs', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='checkout',
            name='expiration_year',
            field=models.IntegerField(choices=[(1, 2022), (2, 2023), (3, 2024), (4, 2025), (5, 2026), (6, 2027), (7, 2028), (8, 2029), (9, 2030)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.country'),
        ),
    ]
