# Generated by Django 4.0.4 on 2022-05-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_country_alter_checkout_expiration_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
    ]
