# Generated by Django 4.0.4 on 2022-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_userreview_rating_alter_userreview_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipping_name',
            field=models.CharField(default='Palli', max_length=100),
            preserve_default=False,
        ),
    ]
