# Generated by Django 4.0.4 on 2022-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_msg_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_replied',
            field=models.DateTimeField(null=True),
        ),
    ]
