# Generated by Django 4.0.4 on 2022-05-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_remove_item_item_item_hitcoun_e60e7c_idx_and_more'),
        ('message', '0002_alter_message_msg_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='msg_history',
        ),
        migrations.AddField(
            model_name='message',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='msg_next',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='msg_next', to='message.message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='org_message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='org_message', to='message.message'),
            preserve_default=False,
        ),
    ]
