# Generated by Django 4.0.4 on 2022-05-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_remove_item_item_item_hitcoun_e60e7c_idx_and_more'),
        ('message', '0003_remove_messagehistory_msg_history_message_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.offer'),
        ),
    ]
